<?php

namespace App;

use Doctrine\ORM\EntityRepository;

/**
 * ReportDataRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ReportDataRepository extends EntityRepository
{
}
